### ISSUE TITLE
Change the text in help command to point to our User Guide

### ISSUE THREAD

**Issue by matthewyip1511** [AY2425S1-CS2103-F12-1/tp#107]
Currently, when one presses the "help" command, you would be met with the following pop-up message:

<img width="553" alt="image" src="https://github.com/user-attachments/assets/40d6a86e-73f5-49a0-bd91-faa9f230f2eb">

This should point to our user guide instead at https://ay2425s1-cs2103-f12-1.github.io/tp/UserGuide.html

**Comment by RezwanAhmed123** [comment]
Fixed in #104

**Comment by RezwanAhmed123** [comment]
Done!
