### ISSUE TITLE
Add UML Sequence Diagram for Close Claim Feature

### ISSUE THREAD

**Issue by yanqiyqh** [AY2425S1-CS2103-F12-1/tp#139]
**Description:**
We have recently implemented the "Close Claim" feature, and it is essential to update the developer guide to include relevant documentation. Specifically, we need to add a UML sequence diagram that illustrates the interactions and processes involved in closing a claim.

**Tasks:**
- Create a UML sequence diagram for the "Close Claim" feature.
- Update the developer guide with the new diagram.
- Ensure that the diagram clearly shows all relevant components and their interactions during the close claim process.

**Acceptance Criteria:**
- The UML sequence diagram is added to the developer guide.
- The diagram accurately represents the workflow of closing a claim.
- Documentation is clear and easy to understand for future developers.

**Additional Notes:**
Please refer to existing diagrams (made using PlantUML) in the developer guide for consistency in style and formatting. If you have any questions or need further clarification on the feature, feel free to reach out.

**Comment by RezwanAhmed123** [comment]
not exactly part of v1.4 as due date is one day later
