### ISSUE TITLE
Add UML Sequence Diagram for Add Insurance Plan Feature

### ISSUE THREAD

**Issue by yanqiyqh** [AY2425S1-CS2103-F12-1/tp#141]
**Description:**
We have implemented the "Add Insurance Plan" feature, and it is important to update the developer guide to include comprehensive documentation. Specifically, we need to create and add a UML sequence diagram that outlines the interactions and processes involved in adding an insurance plan.

**Tasks:**
- Create a UML sequence diagram for the "Add Insurance Plan" feature.
- Update the developer guide with the new diagram.
- Ensure that the diagram clearly illustrates all relevant components and their interactions during the add insurance plan process.

**Acceptance Criteria:**
- The UML sequence diagram is successfully added to the developer guide.
- The diagram accurately reflects the workflow of adding an insurance plan.
- Documentation is clear, concise, and easy to understand for future developers.

**Additional Notes:**
Please refer to existing diagrams (made using PlantUML) in the developer guide for consistency in style and formatting. If you have any questions or need further clarification on the feature, feel free to reach out.

**Comment by RezwanAhmed123** [comment]
not exactly part of v1.4 as due date is one day later
