### ISSUE TITLE
Create Updated Class Diagram for Client Class

### ISSUE THREAD

**Issue by yanqiyqh** [AY2425S1-CS2103-F12-1/tp#142]
**Description:**
We need to create an updated class diagram for the `Client` class that illustrates its attributes and methods, as well as its relationships with the newly implemented `InsurancePlan`, `InsurancePlanManager` and `Claim` classes. This diagram will enhance our documentation and provide a clear understanding of how these components interact.

**Tasks:**
- Design a class diagram for the `Client` class.
- Include relevant attributes and methods for the `Person` class.
- Illustrate the relationships between `Client`, `InsurancePlan`, `InsurancePlanManager`, and `Claim`.
- Update the developer guide with the new class diagram.

**Acceptance Criteria:**
- The class diagram accurately represents the structure of the `Client` class and its interactions.
- The diagram is added to the developer guide in a clear and accessible manner.
- Documentation is consistent with existing diagrams in style and formatting.

**Additional Notes:**
Please ensure that all classes are properly labeled, and consider using UML standards for clarity. If you have any questions or need further clarification on the requirements, feel free to reach out.

**Comment by RezwanAhmed123** [comment]
not exactly part of v1.4 as due date is one day later

**Comment by yanqiyqh** [comment]
Implemented in #153
