### ISSUE TITLE
AddClaim bug: Claim ID is case-sensitive

### ISSUE THREAD

**Issue by zi-yii** [AY2425S1-CS2103-F12-1/tp#174]
Should claim ID "b1234" and"B1234" be considered the same claim?
Ensuring that claim ID is not case sensitive could be less confusing for users. What do all of you think? 🤔 💭 💭 

<img width="707" alt="image" src="https://github.com/user-attachments/assets/4b4c7802-861c-41d0-8cbe-5c34982ae6f0">

**Comment by matthewyip1511** [comment]
I think they should be considered the same claim as it would not be meaningful to differentiate between `b1234` and `B1234`. This can be fixed quite easily by converting all strings to upper case when they are parsed!
