### ISSUE TITLE
AddClaim unable to take in parameters in any order

### ISSUE THREAD

**Issue by zi-yii** [AY2425S1-CS2103-F12-1/tp#182]
Should we implement AddClaim such that parameters can be in any order (as stated in the original user guide)? There is a contradiction between the user guide and AddClaim parser.

When order of parameters is changed, the wrong error message is shown as well.
<img width="863" alt="image" src="https://github.com/user-attachments/assets/dfd625dd-15da-4bed-becf-153976d1c044">

Possible solution 1: Remove the point on "Parameters can be in any order" from the user guide
<img width="835" alt="image" src="https://github.com/user-attachments/assets/0d0f806d-6138-491b-8732-5abfaeaf2776">

Possible solution 2: Implement ability to take in parameters in any order for AddClaim

**Comment by zi-yii** [comment]
I personally think solution 1 would be better

**Comment by RezwanAhmed123** [comment]
i think solution 1 is also best, but if u wanna explore solution 2, maybe we can see how it is done in the "Add" command

**Comment by RezwanAhmed123** [comment]
i fixed it as such in my most recent PR
