### ISSUE TITLE
Naming of insurance plans can be improved in UG

### ISSUE THREAD

**Issue by zi-yii** [AY2425S1-CS2103-F12-1/tp#189]
It would be better to follow how the insurance plans' names are displayed on the GUI. 
We should use "Basic Insurance Plan" and "Travel Insurance Plan".

<img width="768" alt="image" src="https://github.com/user-attachments/assets/de452a53-132a-4ba4-8bee-c69fd40bd1fe">

Note the GUI display here:
<img width="265" alt="image" src="https://github.com/user-attachments/assets/c1b76fc3-3d46-4d67-8baf-702ce980b803">

**Comment by RezwanAhmed123** [comment]
i think its shown based on how they are added, with earliest addition first

**Comment by zi-yii** [comment]
Oops I was not referring to the order. What I meant was instead of writing it as "Basic Plan" and "Travel Insurance", we should name it as "Basic Insurance Plan" and "Travel Insurance Plan".
