### ISSUE TITLE
Grammatical Error in GUI

### ISSUE THREAD

**Issue by yanqiyqh** [AY2425S1-CS2103-F12-1/tp#199]
Currently, we show "1 open claims" when there is 1 open claim for the Client, which is not grammatically sound. Let's change it to "X open claim(s)" to better word our message.

<img width="285" alt="Screenshot 2024-11-05 at 9 31 05 PM" src="https://github.com/user-attachments/assets/43f01be3-8db4-46d6-94e8-7c253e52e680">

**Comment by matthewyip1511** [comment]
Closed in #205
