### ISSUE TITLE
Update the DG: user stories, glossary, NFRs, use cases

### ISSUE THREAD

**Issue by matthewyip1511** [AY2425S1-CS2103-F12-1/tp#20]
more can be found on the website [here] (URL https://nus-cs2103-ay2425s1.github.io/website/schedule/week7/project.html)

**Comment by matthewyip1511** [comment]
more can be found on the website [here] (https://nus-cs2103-ay2425s1.github.io/website/schedule/week7/project.html)

**Comment by RezwanAhmed123** [comment]
All done, updated on numerous PRs.
