### ISSUE TITLE
[PE-D][Tester D] Claim amount of $0 can be done

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-1/tp#227]
![image.png](https://raw.githubusercontent.com/slidings/ped/main/files/71eacdd1-eecb-4ea4-9189-a5d1c023db09.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: slidings/ped#6

**Comment by RezwanAhmed123** [comment]
![image](https://github.com/user-attachments/assets/d86e33d3-10b8-4295-8a8d-b90ea6835f3c)
