### ISSUE TITLE
[PE-D][Tester A] Wrong error message shown for invalid claim amount

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-1/tp#242]
When a claim amount is invalid due to input appending at the back of a number, the following error message is shown. 
![image.png](https://raw.githubusercontent.com/Oceankoh/ped/main/files/3813609f-7853-49a5-b585-2059db531314.png)

This is inconsistent with the usual error message despite both being invalid inputs. 
![image.png](https://raw.githubusercontent.com/Oceankoh/ped/main/files/11823817-69df-4a03-9dc1-6dbe8e236382.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Oceankoh/ped#11

**Comment by RezwanAhmed123** [comment]
any characters after the "." is considered a digit unless its a space

put inside the UG.

**Comment by zi-yii** [comment]
Defense: both are meaningful error messages and similar meaning. Would not really affect user experience
