### ISSUE TITLE
[PE-D][Tester E] Find does not support searching by phone, email, address, tags, insurance, or claim.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-1/tp#245]
The User Guide and app match in that the app does not support find by phone, email, address, tags, insurance, or claim. 

I understand he rationale behind not supporting phone, email, or address as those may not be the most relevant info to filter out searches.

However, in the context of this app, I think finding by tags / type of insurance / claim ID would have been more helpful for better product design.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: youngseopark05/ped#5

**Comment by zi-yii** [comment]
Defense: Agree that finding by tags / type of insurance / claim ID will help to improve product design. However, we did not implement them due to lack of time
