### ISSUE TITLE
[PE-D][Tester A] Overly restrictive insurance plans

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-1/tp#263]
Users can only choose between `Basic Insurance Plan` and `Travel Insurance Plan` to add to clients. 

If the insurance company has more than 2 different plan types, the product becomes unusable. 

There is no way for a user to add additional insurance plan ids, and must rely on the developer pushing insurance plans via software updates. 

Instead of adding insurance plan via id, adding a plan name (understandable to the user) would be fit the use case better.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Oceankoh/ped#15

**Comment by zi-yii** [comment]
Can add to planned enhancements / UG

**Comment by RezwanAhmed123** [comment]
Rejected as this function is usually done by developers in other apps also as name convention needs to be consistent, claim ids should be tailored to specific insurance plans and claim amounts may be calculated differently.
