### ISSUE TITLE
[PE-D][Tester A] Inaccurate documented behavior

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-1/tp#268]
The cautionary message is incorrect

> Caution: If your changes to the data file makes its format invalid, app will discard all data and start with an empty data file at the next run. Hence, it is recommended to take a backup of the file before editing it.

When an invalid edit is made, the data file is not wiped on the start of the next run. It is only overwritten when a command (e.g `list`) is executed. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Oceankoh/ped#16

**Comment by yanqiyqh** [comment]
This is in the UG
