### ISSUE TITLE
[PE-D][Tester B] addClaim - incorrect error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-1/tp#270]
![image.png](https://raw.githubusercontent.com/Vangmay/ped/main/files/19a63d88-102e-4310-a537-3465c0700313.png)

It seems that the command `addClaim 1 iid/1 cid/B1234 ca/+151.10` triggers the error message: The plan with id: 1, has not been added to this client: Alex Yeoh`. To improve user experience, it might be helpful if the error message instead highlights any issues with the command format when that’s the case. This way, users can more easily identify if the issue lies with the command structure rather than the claim status for a specific client.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Vangmay/ped#5

**Comment by yanqiyqh** [comment]
This is not an error message problem but we discover that users are able to add claims with claim amount having the + sign, which is not the intended behavior

**Comment by zi-yii** [comment]
The user input actually has 2 errors.
1. The plan was not added to the client yet. 
2. incorrect format for claim amount

However, the first error (plan not added to client yet) was detected first. Thus the error for claim amount was not shown.

If the plan has already been added to the client, the error for incorrect claim amount format will be triggered.
![Uploading image.png…]()

**Comment by zi-yii** [comment]
We are not allowed to fix code for this as this is an unsuitable value which the app is still working correctly
<img width="728" alt="image" src="https://github.com/user-attachments/assets/18ebb707-4cd4-4425-8b94-50262fcaf092">

**Comment by RezwanAhmed123** [comment]
put in the UG to constrain against $ in the ca being used
